export const hosturl = "http://localhost:3300";
export const endpoints = {
  login: "/api/auth/login",
  getlaptops: "/api/laptops/getall",
  getlaptop: "/api/laptops/get/",
  updatelaptop: "/api/laptops/update/",
  deletelaptop: "/api/laptops/delete/",
  getunassignedlaptops: "/api/laptops/getunassigned",
  addnewlaptop: "/api/laptops/addnew",
  getemployees: "/api/employee/getall",
  getemployee: "/api/employee/get/",
  assignLaptop: "/api/admin/assign",
  unassignLaptop: "/api/admin/unassign/",
  getissues: "/api/admin/issues",
  getrequests: "/api/admin/requests",
  requestAction: "/api/admin/request-action/",
  issueUpdate: "/api/admin/issue/",
  getLogs: "/api/admin/getlogs",
  getcounts: "/api/admin/counts",
};
